using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml;
using Willowsoft.WillowLib.Data.Misc;

namespace Willowsoft.WillowLib.CodeGen
{
    public class TableCreator : CreatorBase
    {
        public TableCreator(TextWriter output, ErrorList errors)
            : base(output, errors)
        {
        }

        public void OutputTableScript(XmlElement parent)
        {
            OutputTableScript(parent, GetEntities(parent));
        }

        private void OutputTableScript(XmlElement parent, XmlElement[] entities)
        {
            XmlElement sqlElement = (XmlElement)parent.SelectSingleNode(DefConstants.SqlElement);
            if (sqlElement == null)
            {
                SevereError("Missing <{0}> element", DefConstants.SqlElement);
                return;
            }
            string role = sqlElement.GetAttribute(DefConstants.SqlRoleAttrib);
            if (string.IsNullOrEmpty(role))
            {
                SevereError("Missing <{0}> [{1}] attribute", DefConstants.SqlElement, DefConstants.SqlRoleAttrib);
                return;
            }
            WriteLine("-- Generated by {0} at {1}", this.GetType().FullName, DateTime.Now);
            if (OutputDrops(entities, role))
                return;
            if (OutputCreates(entities, role))
                return;
        }

        private bool OutputDrops(XmlElement[] entities, string role)
        {
            WriteLine("-- Drop tables and roles");
            WriteLine();
            for (int i = entities.Length - 1; i >= 0; i--)
            {
                string name = entities[i].GetAttribute(DefConstants.EntityClassnameAttrib);
                WriteLine("DROP TABLE dbo.{0}", name);
            }
            WriteLine();
            WriteLine("DROP ROLE {0}", role);
            WriteLine();
            WriteLine("GO");
            WriteLine();
            return false;
        }

        private bool OutputCreates(XmlElement[] entities, string role)
        {
            WriteLine("-- Create tables and roles");
            WriteLine();
            WriteLine("CREATE ROLE {0}", role);
            WriteLine();
            foreach(XmlElement entity in entities)
            {
                if (OutputCreateTable(entity))
                    return true;
            }
            WriteLine("GO");
            WriteLine();
            return false;
        }

        private bool OutputCreateTable(XmlElement entity)
        {
            string classname;
            if (GetClassname(entity, out classname))
                return true;
            WriteLine("CREATE TABLE dbo.{0}", classname);
            WriteLine("(");
            if (OutputTableFields(entity))
                return true;
            if (OutputTableConstraints(entity))
                return true;
            WriteLine(")");
            WriteLine();
            if (OutputIndexes(entity, classname))
                return true;
            return false;
        }

        private bool OutputTableFields(XmlElement entity)
        {
            string idtype;
            if (GetIdtype(entity, out idtype))
                return true;
            WriteLine("    {0} int IDENTITY(1,1) NOT NULL", idtype);
            foreach (XmlElement field in GetFields(entity))
            {
                string fieldName;
                if (GetFieldName(field, out fieldName))
                    return true;
                string sqltype;
                bool isid;
                if (GetSqltype(field, out sqltype, out isid))
                    return true;
                string nullable = field.GetAttribute(DefConstants.FieldNullableAttrib);
                if (string.IsNullOrEmpty(nullable))
                    nullable = "false";
                if (nullable == "false")
                    nullable = "NOT NULL";
                else
                    nullable = "NULL";
                WriteLine("    ,{0} {1} {2}", fieldName, sqltype, nullable);
            }
            WriteLine("    ,CreateDate smalldatetime NOT NULL");
            WriteLine("    ,ModifyDate smalldatetime NOT NULL");
            return false;
        }

        private bool OutputTableConstraints(XmlElement entity)
        {
            XmlNodeList constraints = entity.SelectNodes(DefConstants.SqlElement + "/" +
                DefConstants.SqlConstraintElement);
            foreach (XmlNode constraintNode in constraints)
            {
                XmlElement constraint = (XmlElement)constraintNode;
                string constraintName = constraint.GetAttribute(DefConstants.SqlNameAttrib);
                if (string.IsNullOrEmpty(constraintName))
                    return SevereError("Missing [{0}] attribute on <{1}> element",
                        DefConstants.SqlNameAttrib, DefConstants.SqlConstraintElement);
                string constraintText = constraint.InnerText.Trim();
                WriteLine("    ,CONSTRAINT {0} {1}", constraintName, constraintText);
            }
            return false;
        }

        private bool OutputIndexes(XmlElement entity, string classname)
        {
            XmlNodeList indexes = entity.SelectNodes(DefConstants.SqlElement + "/" +
                DefConstants.SqlIndexElement);
            foreach (XmlNode indexNode in indexes)
            {
                XmlElement index = (XmlElement)indexNode;
                string indexName = index.GetAttribute(DefConstants.SqlNameAttrib);
                if (string.IsNullOrEmpty(indexName))
                    return SevereError("Missing [{0}] attribute on <{1}> element",
                        DefConstants.SqlNameAttrib, DefConstants.SqlIndexElement);
                string unique = index.GetAttribute(DefConstants.SqlIndexUniqueAttrib);
                string uniqueSql = string.Empty;
                if (unique == "true")
                    uniqueSql = " UNIQUE";
                string indexText = index.InnerText.Trim();
                WriteLine("CREATE{3} INDEX {0} ON dbo.{1}({2})", indexName, classname, indexText, uniqueSql);
            }
            WriteLine();
            return false;
        }
    }
}
